// <auto-generated />
namespace BulihanRMS.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update031920 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update031920));
        
        string IMigrationMetadata.Id
        {
            get { return "202003191102075_update-031920"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
